package meta

// embeddedFieldCatalog documents common Insights / entity fields for agent-safe filtering.
// Meta does not expose a stable public Graph field-metadata endpoint for ads_read tokens.
var embeddedFieldCatalog = []fieldContextEntry{
	{Name: "impressions", Levels: []string{"account", "campaign", "adset", "ad"}, Filterable: true, Sortable: true, Description: "Number of times ads were on screen."},
	{Name: "reach", Levels: []string{"account", "campaign", "adset", "ad"}, Filterable: true, Sortable: true, Description: "Number of people who saw ads at least once."},
	{Name: "clicks", Levels: []string{"account", "campaign", "adset", "ad"}, Filterable: true, Sortable: true, Description: "Total clicks on ads."},
	{Name: "spend", Levels: []string{"account", "campaign", "adset", "ad"}, Filterable: true, Sortable: true, Description: "Estimated total amount spent (account currency)."},
	{Name: "results", Levels: []string{"account", "campaign", "adset", "ad"}, Filterable: false, Sortable: true, Description: "Number of results attributed to the optimization goal."},
	{Name: "purchase_roas", Levels: []string{"account", "campaign", "adset", "ad"}, Filterable: false, Sortable: true, Description: "Return on ad spend for purchases."},
	{Name: "cost_per_result", Levels: []string{"account", "campaign", "adset", "ad"}, Filterable: false, Sortable: true, Description: "Average cost per result."},
	{Name: "cost_per_link_click", Levels: []string{"account", "campaign", "adset", "ad"}, Filterable: false, Sortable: true, Description: "Average cost per link click."},
	{Name: "ctr", Levels: []string{"account", "campaign", "adset", "ad"}, Filterable: false, Sortable: true, Description: "Click-through rate."},
	{Name: "cpc", Levels: []string{"account", "campaign", "adset", "ad"}, Filterable: false, Sortable: true, Description: "Average cost per click."},
	{Name: "cpm", Levels: []string{"account", "campaign", "adset", "ad"}, Filterable: false, Sortable: true, Description: "Average cost per 1,000 impressions."},
	{Name: "frequency", Levels: []string{"account", "campaign", "adset", "ad"}, Filterable: false, Sortable: true, Description: "Average impressions per person."},
	{Name: "campaign_id", Levels: []string{"campaign", "adset", "ad"}, Filterable: true, Sortable: false, Description: "Campaign ID."},
	{Name: "campaign_name", Levels: []string{"campaign", "adset", "ad"}, Filterable: true, Sortable: true, Description: "Campaign name."},
	{Name: "adset_id", Levels: []string{"adset", "ad"}, Filterable: true, Sortable: false, Description: "Ad set ID."},
	{Name: "adset_name", Levels: []string{"adset", "ad"}, Filterable: true, Sortable: true, Description: "Ad set name."},
	{Name: "ad_id", Levels: []string{"ad"}, Filterable: true, Sortable: false, Description: "Ad ID."},
	{Name: "ad_name", Levels: []string{"ad"}, Filterable: true, Sortable: true, Description: "Ad name."},
	{Name: "objective", Levels: []string{"campaign"}, Filterable: true, Sortable: false, Description: "ODAX campaign objective (OUTCOME_*)."},
	{Name: "effective_status", Levels: []string{"campaign", "adset", "ad"}, Filterable: true, Sortable: false, Description: "Delivery status considering parent state."},
	{Name: "delivery", Levels: []string{"campaign", "adset", "ad"}, Filterable: true, Sortable: false, Description: "Delivery status summary."},
	{Name: "bid_strategy", Levels: []string{"campaign", "adset"}, Filterable: true, Sortable: false, Description: "Bid strategy (e.g. LOWEST_COST_WITHOUT_CAP)."},
	{Name: "optimization_goal", Levels: []string{"adset"}, Filterable: true, Sortable: false, Description: "Ad set optimization goal."},
	{Name: "attribution_setting", Levels: []string{"adset", "ad"}, Filterable: false, Sortable: false, Description: "Attribution window setting."},
	{Name: "date_start", Levels: []string{"account", "campaign", "adset", "ad"}, Filterable: false, Sortable: false, Description: "Start date for the report row."},
	{Name: "date_stop", Levels: []string{"account", "campaign", "adset", "ad"}, Filterable: false, Sortable: false, Description: "End date for the report row."},
	{Name: "actions:link_click", Levels: []string{"account", "campaign", "adset", "ad"}, Filterable: false, Sortable: false, Description: "Link click actions (use colon fields, not standalone actions)."},
	{Name: "actions:omni_purchase", Levels: []string{"account", "campaign", "adset", "ad"}, Filterable: false, Sortable: false, Description: "Purchase actions across channels."},
	{Name: "actions:like", Levels: []string{"account", "campaign", "adset", "ad"}, Filterable: false, Sortable: false, Description: "Page like actions."},
	{Name: "actions:comment", Levels: []string{"account", "campaign", "adset", "ad"}, Filterable: false, Sortable: false, Description: "Comment actions."},
	{Name: "video_p25_watched_actions", Levels: []string{"account", "campaign", "adset", "ad"}, Filterable: false, Sortable: false, Description: "Video views to 25%."},
	{Name: "video_p50_watched_actions", Levels: []string{"account", "campaign", "adset", "ad"}, Filterable: false, Sortable: false, Description: "Video views to 50%."},
	{Name: "video_p75_watched_actions", Levels: []string{"account", "campaign", "adset", "ad"}, Filterable: false, Sortable: false, Description: "Video views to 75%."},
	{Name: "video_p100_watched_actions", Levels: []string{"account", "campaign", "adset", "ad"}, Filterable: false, Sortable: false, Description: "Video views to 100%."},
}
